UBL_NAMESPACES_PREFIXES = {
            'inv': 'urn:oasis:names:specification:ubl:schema:xsd:Invoice-2',
            'cbc': 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2',
            'cac': 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2',
            'sbd': 'http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader',
            'xades': 'http://uri.etsi.org/01903/v1.3.2#',
            'ad': 'http://www.sovos.com/namespaces/additionalData',
            'sci': 'http://www.sovos.com/namespaces/sovosCanonicalInvoice',
            'svs': 'http://www.sovos.com/namespaces/sovosDocument',
            'sov': 'http://www.sovos.com/namespaces/sovosExtensions',
            'ds': 'http://www.w3.org/2000/09/xmldsig#',
            'ext': 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2',
            'enc':"http://www.sovos.com/namespaces/base64Document" 
        }
UBL_NAMESPACES_PREFIXES_ATTR = {"xmlns": "http://uri.etsi.org/01903/v1.4.1#",
                            "xmlns:sbd": "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader",
                            "xmlns:xades": "http://uri.etsi.org/01903/v1.3.2#",
                            "xmlns:ad": "http://www.sovos.com/namespaces/additionalData",
                            "xmlns:sci": "http://www.sovos.com/namespaces/sovosCanonicalInvoice",
                            "xmlns:svs": "http://www.sovos.com/namespaces/sovosDocument",
                            "xmlns:sov": "http://www.sovos.com/namespaces/sovosExtensions",
                            "xmlns:ds": "http://www.w3.org/2000/09/xmldsig#",
                            "xmlns:cac": "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
                            "xmlns:cbc": "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",
                            "xmlns:ext": "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2",
                            'xmlns:enc':"http://www.sovos.com/namespaces/base64Document",
                            "xmlns:inv": "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"}